### ISSUE TITLE
unit tests for test_vtk.py failing at container and physical machine

### ISSUE THREAD

**Issue by og-analytics** [pmgbergen/porepy#439] opened 2020-07-25 22:22 UTC
Hello,
I am a new user of your fantastic software `porepy`.
The past few days I've been playing a bit with `pypore` and found it very interesting.
I started with the Docker containers and was able to run almost all the notebooks in the tutorial folder with exception of one or two. So, I decided to run the unit tests and see where the problem is coming from.
I run the tests in the container and got this error:
```
------------------------------------------------------------------------------------------------------
TOTAL                                                                    13823   2276    84%

=========================== short test summary info ============================
FAILED test/unit/test_vtk.py::test_single_grid_3d_simplex - assert '<?xml ver...
FAILED test/unit/test_vtk.py::test_single_grid_3d_cart - assert '<?xml versio...
FAILED test/unit/test_vtk.py::test_single_grid_3d_polytop - assert '<?xml ver...
================== 3 failed, 1129 passed in 134.52s (0:02:14) ==================
```

Just curious if this error was due to the container I decided to install `porepy` in my Debian Linux physical machine in a `conda` environment.
I created a `conda` environment using this sequence of commands:

```
conda create -n porepy python=3.7     # create a Python 3.7 environment
conda activate porepy

mkdir ~/python-porepy
cd ~/python-porepy       # any project folder name

wget http://gmsh.info/bin/Linux/gmsh-4.3.0-Linux64.tgz
tar xvf gmsh-4.3.0-Linux64.tgz
echo "config={\"gmsh_path\":\"$PWD/gmsh-4.3.0-Linux64/bin/gmsh\"} " > porepy_config.py

conda install \
   numpy=1.16.3 \
    scipy=1.2.1\
    matplotlib=3.0.3 \
    networkx=2.3 \
    sympy=1.4 \
    cython=0.29.7 \
   pytest-cov=2.6.1 \
   pytest-runner=4.4

conda install -c conda-forge vtk
pip install meshio==2.3.8     shapely==1.6.4.post2     shapely[vectorized]==1.6.4.post2
pip install  gmsh-sdk

git clone https://github.com/pmgbergen/porepy.git pp
cd pp
python setup.py install

cd ..
wget https://raw.githubusercontent.com/keileg/polyhedron/master/polyhedron.py
mv polyhedron.py ./pp/robust_point_in_polyhedron.py
cd pp
pip install -r requirements-dev.txt
python setup.py test
```
Note . I did not install `numba` and `pytest` because the versions provided in this section conflicted with the `requirements-dev.txt` used to install packages for the unit tests.
After running the tests in the physical machine got this:
```
------------------------------------------------------------------------------------------------------
TOTAL                                                                    13823   2277    84%

=============================================== short test summary info ================================================
FAILED test/unit/test_vtk.py::test_single_grid_3d_simplex - assert '<?xml versio...n</VTKFile>\n' == '<?xml versio......
FAILED test/unit/test_vtk.py::test_single_grid_3d_cart - assert '<?xml versio...n</VTKFile>\n' == '<?xml versio...n</...
FAILED test/unit/test_vtk.py::test_single_grid_3d_polytop - assert '<?xml versio...n</VTKFile>\n' == '<?xml versio......
====================================== 3 failed, 1129 passed in 91.35s (0:01:31) =======================================
```
which is the same error as in the container.

Is this error critical? 
Or the reason why the notebook `meshing_of_fractures.ipynb` is crashing with these errors?

![image](https://user-images.githubusercontent.com/67702343/88467281-20935280-ce9b-11ea-9033-49ad98eac82d.png)

and 

![image](https://user-images.githubusercontent.com/67702343/88467294-41f43e80-ce9b-11ea-8aa8-a23391a75c98.png)

Also, the notebook `tracer_transport.ipynb` is producing errors but seem different than those coming from `meshing_of_fractures.ipynb`:

![image](https://user-images.githubusercontent.com/67702343/88467526-9dbfc700-ce9d-11ea-9d7b-b4c9020184c9.png)

![image](https://user-images.githubusercontent.com/67702343/88467531-a6180200-ce9d-11ea-981f-40708c0e1137.png)

![image](https://user-images.githubusercontent.com/67702343/88467535-b203c400-ce9d-11ea-89c0-40b1f7c2a110.png)

![image](https://user-images.githubusercontent.com/67702343/88467540-baf49580-ce9d-11ea-812f-fbb601741806.png)

![image](https://user-images.githubusercontent.com/67702343/88467547-c778ee00-ce9d-11ea-8154-e06a469252f7.png)

**Comment by haakon-e** [comment] 2020-07-26 16:07
Hi,
I'll try to address your issues as best I can.
First of all. Please post the output of `conda list` and verify which branch of porepy you're testing on (I can best help you if you're on `develop` instead of `master`). For any remarks below, I assume you're on `develop`.

Let me start with some introductory remarks.
The Docker images are still very experimental. I have a pending PR with an image you could try out that passes all tests (on develop). See #435. 

As for the conda installation. I'll paste an alternative script below, with some remarks:
```
conda create -n porepy python=3.7     # create a Python 3.7 environment
conda activate porepy

mkdir ~/python-porepy
cd ~/python-porepy       # any project folder name

# No need to install gmsh manually. 
# The pypi installation is sufficient (see below)

# You should be fine without fixing any version numbers.
# You should be fine installing meshio and shapely via conda too.
conda install meshio networkx numpy scipy sympy matplotlib cython future six \
    shapely pytest pytest-cov pytest-runner

# Note: on certain systems, matplotlib requires tornado to be installed 
# separately. It didn't seem like you had that issue, but if so: 
# "conda install tornado" should suffice.

# For vtk, you must ensure you're getting >=9.0. I've had some issues guaranteeing this
# via conda. If vtk=8.1.2, that is probably the reason the `test/unit/test_vtk.py`-tests 
# are failing. Therefore, install via pip instead (this should ensure >=9.0)
pip install vtk

# For gmsh, depending on your linux distro, you might need some additional
# dependencies. If so, execute the first line too, which should be sufficient.
# apt-get install libgl1 libglu1 libxcursor1 libxft2 libxinerama1 -y
pip install gmsh

# Install porepy
git clone https://github.com/pmgbergen/porepy.git pp
# I think since you did "python setup.py install" you're getting the latest release 
# (master branch). Most of the exciting stuff is happening on develop, so I 
# recommend using that. Therefore, install porepy by:
conda install conda-build  # Needed to use "conda develop"
conda develop pp/src  # install the contents of the src folder (i.e. porepy)

# Install robust-point-in-polyhedron
wget https://raw.githubusercontent.com/keileg/polyhedron/master/polyhedron.py
mkdir poly
mv polyhedron.py poly/robust_point_in_polyhedron.py
conda develop poly

# Test
cd pp
python setup.py test
```

1. You should be fine installing the latest versions of all dependencies, including numba and pytest.

2. As mentioned, the errors with `test_vtk.py` are probably due to the version of vtk being 8.1.2 instead of >=9.0.

## Comments on notebooks
### `meshing_of_fractures.ipynb`
#### Screenshot 1
3. I am not able to reproduce this. Please try again after following my instructions above.
#### Screenshot 2
4. I am not able to reproduce this. Please try again after following the instructions above.
### `tracer_transport.ipynb`
#### Screenshot 3
5. I am reproducing this. Will investigate and get back to you.
#### Screenshot 4
6. This seems like the same error as in screenshot 3.
#### Screenshot 5
7. You're not posting the full stack trace. So hard to say, but was initially reproducing something similar; a `KeyError: 'darcy_flux'`. This is because the previous screenshot failed at `pp.plot_grid`, so that `pp.fvutils.compute_darcy_flux` from screenshot 4 didn't run.
#### Screenshot 6
I am not able to reproduce this. This is probably due to the errors you've had above, resulting in certain functions not being run.
#### Screenshot 7
As the error says. The name `tracer` is not defined. See screenshot 6. It fails to define the variable `tracer`.

**Comment by haakon-e** [comment] 2020-07-26 19:41
Hi again @og-analytics,
I believe I tracked down the issue, which is currently under review in #441.
I have run both notebooks with the fix and everything seems to run just fine. Until it is merged, and if you wish to experiment further, you can edit the source files manually (it's just one line, see 90563a4) or checkout the PR branch locally (`origin/fix/plot_grid-0d-grids`)

**Comment by og-analytics** [comment] 2020-07-26 22:54
Hi,
thanks for your feedback.
I am testing on `master`.

Regarding the Docker container, I have been able to produce one that even runs Jupyter.
I don't have any problem at all at reproducing a physical machine behavior in a Docker container. I will later release for your review a new version of a Dockerfile that is living in your `master` branch. We could talk later about a PR.

What gets totally my attention is that the physical machine is showing the same exact errors as the containers. If the physical machine is failing with `porepy` it will be most likely that the containers will fail too, unless is a dependency issue. But all the images I built for `porepy` (three), all are failing the unit tests, including the physical machine. That's why I submitted this.

Now, that you are advising to test with `develop`, I will clone that branch and see what happens.

Thanks,
Alfonso R. Reyes
Houston, Texas

**Comment by og-analytics** [comment] 2020-07-26 23:44
Hello Haakon,
you were right. All the tests are now passing using the `develop` branch. I am sorry about using `master`. I just didn't know. 

```
100, 125, 134-137, 144, 212-213, 219, 237-238, 260, 297, 300, 302-304, 308-309, 314, 342-371, 385, 390, 418, 423, 680, 689-690, 700-701, 724, 739-740, 745-746, 761-762, 793-794, 822-835, 924-1027
src/porepy/viz/fracture_visualization.py                                    58     53     9%   31-124, 148-177
src/porepy/viz/plot_grid.py                                                237    211    11%   62-66, 102-103, 119-120, 123-126, 146-169, 197-246, 258-312, 326-336, 346-349, 359-363, 378-398, 408, 418-443, 460-503, 513-540
------------------------------------------------------------------------------------------------------
TOTAL                                                                    13823   2264    84%


========================================== 1132 passed in 99.30s (0:01:39) ==========================================
```

Possibly, it was the `vtk` version. Now, I am installing `vtk-9.0.1`.

Regarding the `conda` instructions all the lines are fine with exception of `meshio` which doesn't install from the default conda channel; it has to be installed with `pip`:

```
conda create -n porepy-develop python=3.7 -y   # create Python 3.7 environment for porepy-develop
conda activate porepy-develop

mkdir ~/python-porepy
cd ~/python-porepy       # any project folder name

conda install networkx numpy scipy sympy matplotlib cython future six     shapely pytest pytest-cov pytest-runner -y   # meshio will not install from default channel

conda install vtk>=9.0

# meshio-4.0.16
pip install meshio

# vtk-9.0.1
pip install vtk

# all Linux Debian dependencies installed already
sudo apt-get install libgl1 libglu1 libxcursor1 libxft2 libxinerama1 -y

# gmsh-4.6.0
pip install gmsh

# install build capabilities
conda install conda-build 

# clone the source code
git clone https://github.com/pmgbergen/porepy.git pp

# develop mode
conda develop pp/src

# Install robust-point-in-polyhedron
wget https://raw.githubusercontent.com/keileg/polyhedron/master/polyhedron.py
mkdir poly
mv polyhedron.py poly/robust_point_in_polyhedron.py
conda develop poly

# Test
cd pp
python setup.py test
```

I will proceed now to test the notebooks, one by one.

Thanks,
Alfonso R. Reyes

**Comment by og-analytics** [comment] 2020-07-27 03:03
Hello Haakon,
I made this manual change in my `develop` source code:

![image](https://user-images.githubusercontent.com/67702343/88499184-c4a7f700-cf8a-11ea-9f90-3e3e705728b0.png)

Now, the notebook `tracer_transport` is running fine.
![image](https://user-images.githubusercontent.com/67702343/88499238-e43f1f80-cf8a-11ea-9b5a-666e4b6e5f18.png)

And:
![image](https://user-images.githubusercontent.com/67702343/88499263-f28d3b80-cf8a-11ea-833b-07ea191a87a9.png)

What I have noticed that is running different with the `develop` branch is that I now need to install `gmsh-4.6.0-Linux64-sdk`, the `SDK` version of `gmsh`. Before, with `master`, `porepy` was happy with only a small binary from `gmsh-4.3.0-Linux64` and  `echo "config={\"gmsh_path\":\"/home/porepy/gmsh-4.3.0-Linux64/bin/gmsh\"} " > porepy_config.py`. Now, without indicating the `PYTHONPATH` with `export PYTHONPATH=${PYTHONPATH}:$PWD/gmsh-4.6.0-Linux64-sdk/lib`, `porepy` will not import because `gmsh` wants `SDK`. I will report this in a separate issue.

Thanks.

PS. I think we could close this one.

**Comment by haakon-e** [comment] 2020-07-27 05:57
This is a comment that's really hard to read

**Comment by haakon-e** [comment] 2020-07-27 06:13
Hi @og-analytics,
I'm happy it worked out.

For meshio, you could try to add the option `conda install -c conda-forge meshio` to install from [conda-forge](https://anaconda.org/conda-forge/meshio)).

Just to be clear. master branch, i.e. v1.1.0, should work for all ordinary simulations. It's just a long time since we updated, so I'm less experienced working on that branch compared to some of the other people in the group.

-Haakon

**Closed** 2020-07-27 06:14 UTC
