### ISSUE TITLE
Warnings in pytest

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#187] opened 2018-12-07 13:21 UTC
Running pytest raises an awful lot of warnings, caused e.g. by deprecated functions from external dependencies.

**Comment by keileg** [comment] 2018-12-07 13:22
Quite a few of the problems is caused by functions I have implemented, so I will have the first go.

**Comment by IvarStefansson** [comment] 2019-01-16 09:36
This has improved a lot! I would say yes, we can close it. If somebody were to get rid of the following two warnings, we would be down to about ten warnings.

/anaconda3/envs/porepy/lib/python3.6/site-packages/vtk/util/numpy_support.py:134: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \

anaconda3/envs/porepy/lib/python3.6/site-packages/scipy/sparse/compressed.py:742: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)

**Comment by keileg** [comment] 2019-01-16 10:20
The first one, I believe is related to the vtk interface. Is that correct, @alessiofumagalli ?

The second one annoys me as well. I will try to find it.

**Comment by keileg** [comment] 2019-05-09 11:56
This seems to be acceptable now, so I'll close it.

**Closed by keileg** 2019-05-09 11:56 UTC
